spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cinema?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: cdx548205644

cinema:
  jwt:
    secret: cinema-jwt-secret-key-2024
